language: python
python:
  - "3.5"
  - "3.6"
install:
  - python -m pip install -r requirements.txt
  - python -m pip install -r testing_requirements.txt
  - python setup.py install
script:
  - chmod +x test/travis.sh
  - test/travis.sh