language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
notifications:
  email:
    on_failure: change
install:
  - python -m pip install -r requirements.txt
  - python -m pip install -r testing_requirements.txt
  - python setup.py install
script:
  - pwd
  - cd tests
  - python run_doctest.py
  - python run_pytest.py
  - cd /home/travis/build/Chris-Johnston/Easier68k
  - (find easier68k -iname "*.py" | xargs pylint) || true
  - (find tests/ -iname "*.py" | xargs pylint) || true
