language: python
python:
  - "3.5"
  - "3.6"
install:
  - python -m pip install -r requirements.txt
  - python -m pip install -r testing_requirements.txt
  - python setup.py install
script:
  - pwd
  - cd tests
  - python run_doctest.py
  - python run_pytest.py
