from .opcode import Opcode
from .add import Add
from .adda import Adda
from .bcc import Bcc, Bcs, Beq, Bge, Bgt, Bhi, Ble, Bls, Blt, Bmi, Bne
from .cmp import Cmp
from .cmpi import Cmpi
from .dc import DC
from .eor import Eor
from .jsr import Jsr
from .lea import Lea
from .move import Move
from .movea import Movea
from .neg import Neg
from .opcode_or import Or
from .ori import Ori
from .rts import Rts
from .simhalt import Simhalt
from .sub import Sub
from .subq import Subq
from .trap import Trap